In [1]:
import torch
from torch import nn
from deeplotx import MultiHeadFeedForward
from stable_baselines3.common.policies import ActorCriticPolicy


class MyActorCriticPolicy(nn.Module):
    def __init__(self, feature_dim: int, policy_output_dim: int, value_output_dim: int, device: str = 'cpu', dtype: torch.dtype = torch.float32):
        super().__init__()  
        self.latent_dim_pi = policy_output_dim  
        self.latent_dim_vf = value_output_dim  
        self.policy_net = nn.Sequential(  
            MultiHeadFeedForward(feature_dim=feature_dim, num_heads=3, device=device, dtype=dtype), nn.Linear(in_features=feature_dim, out_features=policy_output_dim, device=torch.device(device), dtype=dtype)
        )  
        self.value_net = nn.Sequential(  
            MultiHeadFeedForward(feature_dim=feature_dim, num_heads=3, device=device, dtype=dtype), nn.Linear(in_features=feature_dim, out_features=value_output_dim, device=torch.device(device), dtype=dtype)
        )
    
    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        return self.policy_net.forward(x), self.value_net.forward(x)
    
    def forward_actor(self, x: torch.Tensor):  
        return self.policy_net.forward(x)  
  
    def forward_critic(self, x: torch.Tensor):  
        return self.value_net.forward(x)


class MyRLModel(ActorCriticPolicy):
    def _build_mlp_extractor(self) -> None:  
        self.mlp_extractor = MyActorCriticPolicy(self.features_dim, 64, 64)

In [2]:
import gymnasium
from stable_baselines3 import PPO

env = gymnasium.make("CartPole-v1", render_mode="human")
ppo = PPO(MyRLModel, env, verbose=1)
ppo.learn(total_timesteps=3000, progress_bar=True)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


Output()

D:\project\RL-Example\.venv\Lib\site-packages\pygame\pkgdata.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_stream, resource_exists


---------------------------------
| rollout/           |          |
|    ep_len_mean     | 21       |
|    ep_rew_mean     | 21       |
| time/              |          |
|    fps             | 46       |
|    iterations      | 1        |
|    time_elapsed    | 44       |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 27.8        |
|    ep_rew_mean          | 27.8        |
| time/                   |             |
|    fps                  | 45          |
|    iterations           | 2           |
|    time_elapsed         | 89          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.016178887 |
|    clip_fraction        | 0.17        |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    explained_variance   | 0.00107     |
|    learning_rate        | 0.

In [4]:
vec_env = ppo.get_env()
obs = vec_env.reset()
for i in range(1000):
    action, _states = ppo.predict(obs, deterministic=True)
    obs, reward, done, info = vec_env.step(action)
    print(action, _states)
    print(obs, reward, done, info)
    # VecEnv resets automatically
    if done:
      obs = vec_env.reset()

[0] None
[[ 0.04188522 -0.21507557  0.02585348  0.30617347]] [1.] [False] [{'TimeLimit.truncated': False}]
[1] None
[[ 0.03758371 -0.02033139  0.03197695  0.0217549 ]] [1.] [False] [{'TimeLimit.truncated': False}]
[1] None
[[ 0.03717708  0.17431773  0.03241205 -0.26066992]] [1.] [False] [{'TimeLimit.truncated': False}]
[0] None
[[ 0.04066344 -0.02125155  0.02719865  0.04205742]] [1.] [False] [{'TimeLimit.truncated': False}]
[1] None
[[ 0.04023841  0.17347004  0.0280398  -0.24192151]] [1.] [False] [{'TimeLimit.truncated': False}]
[0] None
[[ 0.04370781 -0.02204099  0.02320137  0.05947237]] [1.] [False] [{'TimeLimit.truncated': False}]
[1] None
[[ 0.04326699  0.17274074  0.02439081 -0.225801  ]] [1.] [False] [{'TimeLimit.truncated': False}]
[0] None
[[ 0.0467218  -0.02272114  0.01987479  0.07447481]] [1.] [False] [{'TimeLimit.truncated': False}]
[1] None
[[ 0.04626738  0.17211032  0.02136429 -0.21187188]] [1.] [False] [{'TimeLimit.truncated': False}]
[0] None
[[ 0.04970958 -0.02331047  0